---
collections:
  - name: git+https://github.com/eingram23/ansible-col-homelab.git
    type: git
    version: main
  - name: git+https://github.com/eingram23/ansible-col-pihol.git
    type: git
    version: main