---
collections:
  - name: https://github.com/eingram23/ansible-col-homelab.git
    type: git
    version: main
  - name: https://github.com/eingram23/ansible-col-pihole.git
    type: git
    version: main
  - name: https://github.com/eingram23/ansible-col-tf-build.git
    type: git
    version: main