---
- name: Check if project folder already exists
  ansible.builtin.stat:
    path: "{{proj_root}}{{proj_name}}"
  register: project

- name: Check to see if project folder exists
  when: not project.stat.exists
  block:
    - name: Create Terraform project folder
      ansible.builtin.file:
        path: "{{proj_root}}{{proj_name}}"
        state: directory

    - name: Copy template files into project folder
      ansible.builtin.copy: 
        src: "{{temp_path}}"
        dest: "{{proj_root}}{{proj_name}}/"

- name: Create creds file
  ansible.builtin.template:
    src: creds.json.j2
    dest: /terraform/creds.json
    mode: 0400    

- name: Run Terraform Apply
  community.general.terraform:
    force_init: true
    project_path: "{{proj_root}}{{proj_name}}"
    state: present
    variables:
      proj_name: "{{ proj_name }}"
      # gcp_project: "{{ gcp_project }}"
      # gcp_region: "{{ gcp_region }}"
      # gcp_zone: "{{ gcp_zone }}"
      vsphere_template: "{{vsphere_template}}"
      vsphere_datastore_list: "{{vsphere_datastore_list|to_json}}"
      vsphere_network_list: "{{vsphere_network_list|to_json}}"
      vm_folder_name: "{{vm_folder_name}}"
      vm_name_list: "{{vm_name_list|to_json}}"
      ip_address_list: "{{ip_address_list|to_json}}"
      ip_gateway_list: "{{ip_gateway_list|to_json}}"
      vm_ram: "{{vm_ram}}"
      vm_cpu: "{{vm_cpu}}"
      dns_suffix_list: "{{dns_suffix_list|to_json}}"
      workgroup: "{{workgroup|default([])}}"
