---
- name: Create Ansible inventory entries
  ini_file:
    dest: /Users/edwardingram/code/Ansible/hosts
    section: "{{ansible_group}}"
    option: "{{ item }}.{{dns_suffix_list[0]}}"
    allow_no_value: yes
  loop: "{{vm_name_list}}"

- name: Refresh metadata
  meta: refresh_inventory
    
