---
- name: Remove hosts from known_hosts
  lineinfile:
    backup: yes
    path: /Users/edwardingram/.ssh/known_hosts
    regexp: "{{ item }}.{{dns_suffix_list[0]}}"
    state: absent
  loop: "{{vm_name_list}}"