---
# TAGS - snmpd, splunk, container_host, webapps, node_exporter
- name: Deploy new server(s) - run roles against piholes
  hosts: piholes
  gather_facts: false
  become: true
  become_method: sudo
  vars_files:
    - ../vars/vars-linux-rocky2.yaml
  
  tasks:

    - name: Import pihole-add role
      import_role:
        name: eingram23.pihole.pihole-add
      tags: 
        - always

- name: Run localhost roles
  hosts: localhost
  gather_facts: false
  become: false
  vars_files:
    - vars.yaml

  tasks:

    - name: Import inmem-inv role
      import_role:
        name: inmem-inv 
      tags: 
        - always
    - name: Import terraform-apply role
      import_role:
        name: terraform-apply
      tags:
        - always

- name: Run roles against new server(s)
  hosts: temp_group
  become: true
  become_method: sudo

  roles:
    - role: rhel-sub-add
      when: ansible_facts['distribution'] == 'RedHat'
      tags:
        - always
    - role: add-eingram-user
      tags:
        - always
    - role: chrony
      tags:
        - always
    - role: install-core-pkgs
      tags:
        - always
    - role: container-host
      tags:
        - container-host
        - never
    - role: webapps
      tags:
        - webapps
        - never
    - role: splunk-uf
      tags:
        - splunk-uf
        - never
    - role: snmpd
      tags:
        - snmpd
        - never
    - role: node-exporter
      tags:
        - node-exporter
        - never

- name: Add target to prometheus server
  hosts: grafana.local.lan
  gather_facts: false
  become: true
  become_user: poduser
  become_method: sudo
  vars_files:
    - vars.yaml

  tasks:
  
    - name: Import prometheus-target-update-nix role
      import_role:
        name: prometheus-target-update-nix
      tags:
        - node-exporter
        - never
