---
- name: Remove project servers and clean inventory/DNS
  hosts: localhost
  gather_facts: false
  become: false
  vars_files:
    - vars.yaml

  tasks:

    - name: Create in memory inventory
      add_host:
        name: "{{ item }}.{{ dns_suffix_list[0] }}"
        groups: temp_group
      loop: "{{ vm_name_list}}"
      
- hosts: temp_group
  become: true
  become_method: sudo

  vars:
    - rolepath: "../../homelab/roles/"

  roles:
    - role: "{{rolepath}}rhel_sub_del"
      when: ansible_facts['distribution'] == 'RedHat'
      
- name: Destroy Terraform
  hosts: localhost
  gather_facts: false
  become: false
  vars_files:
    - vars.yaml

  roles:
    - remove_hosts_inv
    - terraform_destroy
    - remove_known_hosts
 
- name: Run terraform destroy and clean inventory/dns
  hosts: piholes
  gather_facts: false
  remote_user: eingram
  become: true
  become_method: sudo
  vars_files:
    - vars.yaml
  
  roles:
    - pihole_remove